{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "19f45a62",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Completed ✅ File saved as:\n",
      "D:\\2025-MRO-SP\\python\\Tag Comprasion code\\Pin Generation\\R1-complete Rows_PIN_Generated.xlsx\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "from pathlib import Path\n",
    "from openpyxl import load_workbook\n",
    "from openpyxl.styles import PatternFill\n",
    "\n",
    "# =======================\n",
    "# FILE SETUP\n",
    "# =======================\n",
    "folder_path = r\"D:\\2025-MRO-SP\\python\\Tag Comprasion code\\Pin Generation\"\n",
    "excel_files = list(Path(folder_path).glob(\"*.xlsx\"))\n",
    "\n",
    "if not excel_files:\n",
    "    raise FileNotFoundError(\"No Excel files found in the folder\")\n",
    "\n",
    "file_path = excel_files[0]\n",
    "df = pd.read_excel(file_path)\n",
    "df.columns = df.columns.str.strip()\n",
    "\n",
    "# =======================\n",
    "# HELPER FUNCTIONS\n",
    "# =======================\n",
    "def contains_map(text, mapping, default=\"\"):\n",
    "    if pd.isna(text):\n",
    "        return default\n",
    "    text = str(text)\n",
    "    for key, value in mapping.items():\n",
    "        if key in text:\n",
    "            return value\n",
    "    return default\n",
    "\n",
    "def extract_after_dash(text, index):\n",
    "    if pd.isna(text) or \"-\" not in str(text):\n",
    "        return \"\"\n",
    "    part = str(text).split(\"-\", 1)[1]\n",
    "    return part[index] if len(part) > index else \"\"\n",
    "\n",
    "# =======================\n",
    "# MODEL NUMBER\n",
    "# =======================\n",
    "model_map = {\n",
    "    \"-5\": \"05\", \"-10\": \"10\", \"-18\": \"18\", \"-21\": \"21\",\n",
    "    \"-33\": \"33\", \"-35\": \"35\", \"-41\": \"41\",\n",
    "    \"-77\": \"77\", \"-78\": \"78\", \"-80\": \"80\"\n",
    "}\n",
    "df[\"Model Number-Code\"] = df[\"Model Number\"].apply(lambda x: contains_map(x, model_map))\n",
    "\n",
    "# =======================\n",
    "# SIZE\n",
    "# =======================\n",
    "size_map = {\n",
    "    \"0.5 x\": \"05\", \"0.7 x\": \"75\", \"1 x\": \"01\", \"1.5 x\": \"15\",\n",
    "    \"2 x\": \"02\", \"3 x\": \"03\", \"4 x\": \"04\", \"6 x\": \"06\",\n",
    "    \"8 x\": \"08\", \"10 x\": \"10\", \"12 x\": \"12\", \"14 x\": \"14\",\n",
    "    \"16 x\": \"16\", \"18 x\": \"18\", \"20 x\": \"20\", \"24 x\": \"24\",\n",
    "    \"26 x\": \"26\", \"28 x\": \"28\", \"30 x\": \"30\",\n",
    "    \"36 x\": \"36\", \"40 x\": \"40\", \"42 x\": \"42\", \"48 x\": \"48\"\n",
    "}\n",
    "df[\"In x Body x Out Size-Code\"] = df[\"In x Body x Out Size\"].apply(lambda x: contains_map(x, size_map))\n",
    "\n",
    "# =======================\n",
    "# RATING CLASS\n",
    "# =======================\n",
    "rating_map = {\n",
    "    \"150\": \"1\", \"300\": \"2\", \"600\": \"3\",\n",
    "    \"800\": \"4\", \"900\": \"5\", \"1500\": \"6\", \"2500\": \"7\"\n",
    "}\n",
    "df[\"Rating Class-Code\"] = df[\"Rating Class\"].apply(lambda x: contains_map(x, rating_map))\n",
    "\n",
    "# =======================\n",
    "# END CONNECTION\n",
    "# =======================\n",
    "end_conn_map = {\n",
    "    \"RF\": \"RF\", \"FF\": \"FF\", \"RTJ\": \"RJ\",\n",
    "    \"Lugged\": \"LG\", \"BW\": \"BW\", \"SW\": \"SW\"\n",
    "}\n",
    "df[\"End Connection-Code\"] = df[\"End Connection\"].apply(lambda x: contains_map(x, end_conn_map))\n",
    "\n",
    "# =======================\n",
    "# BODY MATERIAL\n",
    "# =======================\n",
    "body_mat_map = {\n",
    "    \"WCC\": \"A\", \"LCC\": \"B\", \"A105\": \"C\", \"LF2\": \"D\",\n",
    "    \"CF8 \": \"E\", \"CF3 \": \"F\", \"CF8M\": \"G\", \"CF3M\": \"H\",\n",
    "    \"Duplex\": \"I\", \"Super Duplex\": \"J\", \"Aluminum Bronze\": \"K\"\n",
    "}\n",
    "df[\"Body Material-Code\"] = df[\"Body Material\"].apply(lambda x: contains_map(x, body_mat_map))\n",
    "\n",
    "# =======================\n",
    "# BODY STUDS\n",
    "# =======================\n",
    "df[\"Body Studs-Code\"] = df[\"Body Studs\"].apply(\n",
    "    lambda x: \"2\" if pd.notna(x) and \"coat\" in str(x).lower() else \"1\"\n",
    ")\n",
    "\n",
    "# =======================\n",
    "# BONNET TYPE\n",
    "# =======================\n",
    "bonnet_map = {\n",
    "    \"Standard\": \"ST\",\n",
    "    \"Extended\": \"EB\",\n",
    "    \"Finned\": \"FB\"\n",
    "}\n",
    "df[\"Bonnet Type-Code\"] = df[\"Bonnet Type\"].apply(lambda x: contains_map(x, bonnet_map, \"NA\"))\n",
    "\n",
    "# =======================\n",
    "# ACTUATOR MODEL\n",
    "# =======================\n",
    "act_model_map = {\n",
    "    \"Top Mounted Handwheel\": \"20\",\n",
    "    \"87\": \"87\", \"88\": \"88\",\n",
    "    \"51\": \"51\", \"52\": \"52\", \"53\": \"53\",\n",
    "    \"37\": \"37\", \"38\": \"38\",\n",
    "    \"Electrical Linear\": \"EL\",\n",
    "    \"Electrical Rotary\": \"ER\"\n",
    "}\n",
    "df[\"Actuator Model-Code\"] = df[\"Actuator Model\"].apply(lambda x: contains_map(x, act_model_map))\n",
    "\n",
    "# =======================\n",
    "# ACTUATOR SIZE\n",
    "# =======================\n",
    "act_size_map = {\n",
    "    \"6\": \"A\", \"12\": \"B\", \"16\": \"C\", \"20\": \"D\",\n",
    "    \"23L\": \"F\", \"23\": \"E\", \"11\": \"G\", \"13\": \"H\",\n",
    "    \"15\": \"I\", \"18\": \"J\", \"24\": \"K\",\n",
    "    \"Electric\": \"L\", \"10\": \"M\"\n",
    "}\n",
    "df[\"Actuator Size-Code\"] = df[\"Actuator Size\"].apply(lambda x: contains_map(x, act_size_map))\n",
    "\n",
    "# =======================\n",
    "# PLUG MATERIAL\n",
    "# =======================\n",
    "def plug_material_code(text):\n",
    "    if pd.isna(text):\n",
    "        return \"\"\n",
    "    t = str(text)\n",
    "    if \"316\" in t and (\"Hard\" in t or \"HF\" in t):\n",
    "        return \"1\"\n",
    "    if \"316\" in t:\n",
    "        return \"2\"\n",
    "    if \"410\" in t:\n",
    "        return \"3\"\n",
    "    if \"CA6NM\" in t:\n",
    "        return \"4\"\n",
    "    return \"\"\n",
    "\n",
    "df[\"Plug Material-Code\"] = df[\"Plug Material\"].apply(plug_material_code)\n",
    "\n",
    "# =======================\n",
    "# TRIM / SEAT FROM MODEL\n",
    "# =======================\n",
    "df[\"Plug Type-Code\"] = df[\"Model Number\"].apply(lambda x: extract_after_dash(x, 2))\n",
    "df[\"Trim Type-Code\"] = df[\"Model Number\"].apply(lambda x: extract_after_dash(x, 3))\n",
    "df[\"Seat Type-Code\"] = \"\"\n",
    "\n",
    "# =======================\n",
    "# TRIM CHARACTERISTIC\n",
    "# =======================\n",
    "trim_char_map = {\n",
    "    \"Linear\": \"1\",\n",
    "    \"Equal Percentage\": \"2\",\n",
    "    \"EQ\": \"2\",\n",
    "    \"Modified Percentage\": \"3\",\n",
    "    \"Quick Opening\": \"4\"\n",
    "}\n",
    "df[\"Trim Characteristic-Code\"] = df[\"Trim Characteristic\"].apply(lambda x: contains_map(x, trim_char_map))\n",
    "\n",
    "# =======================\n",
    "# PIN CODE\n",
    "# =======================\n",
    "pin_columns = [\n",
    "    \"Model Number-Code\",\n",
    "    \"In x Body x Out Size-Code\",\n",
    "    \"Rating Class-Code\",\n",
    "    \"End Connection-Code\",\n",
    "    \"Body Material-Code\",\n",
    "    \"Body Studs-Code\",\n",
    "    \"Bonnet Type-Code\",\n",
    "    \"Actuator Model-Code\",\n",
    "    \"Actuator Size-Code\",\n",
    "    \"Plug Material-Code\",\n",
    "    \"Trim Type-Code\",\n",
    "    \"Seat Type-Code\",\n",
    "    \"Trim Characteristic-Code\"\n",
    "]\n",
    "\n",
    "df[\"PIN-Code\"] = df[pin_columns].fillna(\"\").astype(str).agg(\"\".join, axis=1)\n",
    "\n",
    "# =======================\n",
    "# PIN DESCRIPTION\n",
    "# =======================\n",
    "desc_columns = [\n",
    "    \"Model Number\",\n",
    "    \"In x Body x Out Size\",\n",
    "    \"Rating Class\",\n",
    "    \"End Connection\",\n",
    "    \"Body Material\",\n",
    "    \"Body Studs\",\n",
    "    \"Bonnet Type\",\n",
    "    \"Actuator Model\",\n",
    "    \"Actuator Size\",\n",
    "    \"Plug Material\",\n",
    "    \"Trim Type\",\n",
    "    \"Seat Type\",\n",
    "    \"Trim Characteristic\"\n",
    "]\n",
    "\n",
    "df[\"PIN-Code description\"] = df[desc_columns].fillna(\"\").astype(str).agg(\", \".join, axis=1)\n",
    "\n",
    "# =======================\n",
    "# SAVE FILE\n",
    "# =======================\n",
    "output_file = file_path.with_name(file_path.stem + \"_PIN_Generated.xlsx\")\n",
    "df.to_excel(output_file, index=False)\n",
    "\n",
    "# =======================\n",
    "# FORMATTING\n",
    "# =======================\n",
    "wb = load_workbook(output_file)\n",
    "ws = wb.active\n",
    "\n",
    "green_fill = PatternFill(start_color=\"92D050\", end_color=\"92D050\", fill_type=\"solid\")\n",
    "yellow_fill = PatternFill(start_color=\"FFFF00\", end_color=\"FFFF00\", fill_type=\"solid\")\n",
    "\n",
    "new_columns = [\n",
    "    \"Model Number-Code\",\n",
    "    \"In x Body x Out Size-Code\",\n",
    "    \"Rating Class-Code\",\n",
    "    \"End Connection-Code\",\n",
    "    \"Body Material-Code\",\n",
    "    \"Body Studs-Code\",\n",
    "    \"Bonnet Type-Code\",\n",
    "    \"Actuator Model-Code\",\n",
    "    \"Actuator Size-Code\",\n",
    "    \"Plug Material-Code\",\n",
    "    \"Plug Type-Code\",\n",
    "    \"Trim Type-Code\",\n",
    "    \"Seat Type-Code\",\n",
    "    \"Trim Characteristic-Code\",\n",
    "    \"PIN-Code\",\n",
    "    \"PIN-Code description\"\n",
    "]\n",
    "\n",
    "header_map = {\n",
    "    ws.cell(row=1, column=col).value: col\n",
    "    for col in range(1, ws.max_column + 1)\n",
    "}\n",
    "\n",
    "for col_name in new_columns:\n",
    "    if col_name not in header_map:\n",
    "        continue\n",
    "\n",
    "    col_idx = header_map[col_name]\n",
    "    ws.cell(row=1, column=col_idx).fill = green_fill\n",
    "\n",
    "    for row in range(2, ws.max_row + 1):\n",
    "        cell = ws.cell(row=row, column=col_idx)\n",
    "        if cell.value is None or str(cell.value).strip() == \"\":\n",
    "            cell.fill = yellow_fill\n",
    "\n",
    "wb.save(output_file)\n",
    "\n",
    "print(f\"Completed ✅ File saved as:\\n{output_file}\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
